# This file is a template, and might need editing before it works on your project.
# Official docker image.
#
before_script:
  - docker info

build:
  stage: build
  script:
    - docker build --add-host=registry.npm.taobao.org:114.55.80.225 -t ipc-proxy .
    - docker rm -f ipc-proxy || true
    - docker run -d --restart always --name ipc-proxy --network ipc2 -e SRS_HOST=srs -e SRS_PORT=8000 -e WS_PORT=4010 -p 4010:4010 ipc-proxy
  only:
    - develop
