# This file is a template, and might need editing before it works on your project.
# Official docker image.
#    - docker rm -f ipc-gateway || true
#    - docker run -d --restart always --name ipc-gateway --network ipc2 -e FFMPEG_SERVICE_HOST=ipc-ffmpeg -e FFMPEG_SERVICE_PORT=8080 -e IPC_SERVICE_HOST=ipc-server -e IPC_SERVICE_PORT=8080 -p 8083:8080 ipc-gateway
#
before_script:
  - docker info
  - docker login -u dockerClient -p DczMTUzODcz localhost:5000

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build . --add-host=registry.npm.taobao.org:114.55.80.225 -t localhost:5000/ipc-proxy
    - docker push localhost:5000/ipc-proxy
  only:
    - develop
    - master

deploy-beta:
  stage: deploy
  script:
    - ssh beta docker login -u dockerClient -p DczMTUzODcz 101.254.255.75:5000
    - ssh beta docker pull 101.254.255.75:5000/ipc-proxy
    - ssh beta docker rm -f ipc-proxy || true
    - ssh beta docker run -d --restart always --name ipc-proxy --network ipc2 -e SRS_HOST=srs -e SRS_PORT=8000 -e WS_PORT=4010 -p 4010:4010 101.254.255.75:5000/ipc-proxy
  only:
    - develop

deploy-prod:
  stage: deploy
  script:
    - ssh prod docker login -u dockerClient -p DczMTUzODcz 101.254.255.75:5000
    - ssh prod docker pull 101.254.255.75:5000/ipc-proxy
    - ssh prod docker rm -f ipc-proxy || true
    - ssh prod docker run -d --restart always --name ipc-proxy --network ipc -e SRS_HOST=srs -e SRS_PORT=8000 -e WS_PORT=4010 -p 4010:4010 101.254.255.75:5000/ipc-proxy
  only:
    - master
